In [34]:
!pip install nltk


In [67]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk

In [36]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [37]:
# Tokenization
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [38]:
tokens = word_tokenize(document.lower())

In [39]:
# build vocab
vocab = {'<unk>':0}

for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token] = len(vocab)

vocab

{'<unk>': 0,
 'about': 1,
 'the': 2,
 'program': 3,
 'what': 4,
 'is': 5,
 'course': 6,
 'fee': 7,
 'for': 8,
 'data': 9,
 'science': 10,
 'mentorship': 11,
 '(': 12,
 'dsmp': 13,
 '2023': 14,
 ')': 15,
 'follows': 16,
 'a': 17,
 'monthly': 18,
 'subscription': 19,
 'model': 20,
 'where': 21,
 'you': 22,
 'have': 23,
 'to': 24,
 'make': 25,
 'payments': 26,
 'of': 27,
 'rs': 28,
 '799/month': 29,
 '.': 30,
 'total': 31,
 'duration': 32,
 '?': 33,
 '7': 34,
 'months': 35,
 'so': 36,
 'becomes': 37,
 '799': 38,
 '*': 39,
 '=': 40,
 '5600': 41,
 'approx': 42,
 'syllabus': 43,
 'we': 44,
 'will': 45,
 'be': 46,
 'covering': 47,
 'following': 48,
 'modules': 49,
 ':': 50,
 'python': 51,
 'fundamentals': 52,
 'libraries': 53,
 'analysis': 54,
 'sql': 55,
 'maths': 56,
 'machine': 57,
 'learning': 58,
 'ml': 59,
 'algorithms': 60,
 'practical': 61,
 'mlops': 62,
 'case': 63,
 'studies': 64,
 'can': 65,
 'check': 66,
 'detailed': 67,
 'here': 68,
 '-': 69,
 'https': 70,
 '//learnwith.campusx.i

In [40]:
len(vocab)

289

In [41]:
input_sentences = document.split('\n')

In [42]:
input_sentences

['About the Program',
 'What is the course fee for  Data Science Mentorship Program (DSMP 2023)',
 'The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.',
 'What is the total duration of the course?',
 'The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)',
 'What is the syllabus of the mentorship program?',
 'We will be covering the following modules:',
 'Python Fundamentals',
 'Python libraries for Data Science',
 'Data Analysis',
 'SQL for Data Science',
 'Maths for Machine Learning',
 'ML Algorithms',
 'Practical ML',
 'MLOPs',
 'Case studies',
 'You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390',
 'Will Deep Learning and NLP be a part of this program?',
 'No, NLP and Deep Learning both are not a part of this program’s curriculum.',
 'What if I miss a live session? Will I get a recording 

In [43]:
def text_to_indices(sentence , vocab):
  numerical_sentence = []
  for token in word_tokenize(sentence.lower()):
    if token not in vocab:
      numerical_sentence.append(vocab['<unk>'])
    else:
      numerical_sentence.append(vocab[token])
  return numerical_sentence

In [44]:
len(input_sentences)

78

In [45]:
input_numerical_sentence = []
for sentence in input_sentences:
  input_numerical_sentence.append(text_to_indices(sentence , vocab))

In [46]:
input_numerical_sentence

[[1, 2, 3],
 [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14, 15],
 [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27, 28, 29, 30],
 [4, 5, 2, 31, 32, 27, 2, 6, 33],
 [2,
  31,
  32,
  27,
  2,
  6,
  5,
  34,
  35,
  30,
  36,
  2,
  31,
  6,
  7,
  37,
  38,
  39,
  34,
  40,
  28,
  41,
  12,
  42,
  30,
  15],
 [4, 5, 2, 43, 27, 2, 11, 3, 33],
 [44, 45, 46, 47, 2, 48, 49, 50],
 [51, 52],
 [51, 53, 8, 9, 10],
 [9, 54],
 [55, 8, 9, 10],
 [56, 8, 57, 58],
 [59, 60],
 [61, 59],
 [62],
 [63, 64],
 [22, 65, 66, 2, 67, 43, 68, 69, 70, 50, 71],
 [45, 72, 58, 73, 74, 46, 17, 75, 27, 76, 3, 33],
 [77, 78, 74, 73, 72, 58, 79, 80, 81, 17, 75, 27, 76, 3, 82, 83, 84, 30],
 [4, 85, 86, 87, 17, 88, 89, 33, 45, 86, 90, 17, 91, 27, 2, 89, 33],
 [92,
  93,
  94,
  95,
  80,
  96,
  78,
  36,
  97,
  85,
  22,
  87,
  17,
  89,
  22,
  65,
  98,
  99,
  73,
  100,
  2,
  91,
  30],
 [21, 65, 86, 101, 2, 102, 103, 33],
 [104,
  76,
  105,
  106,
  24,
  107,
  108,
  109,
  108,
  110,
  111,
  27,

In [47]:
len(input_numerical_sentence)

78

In [48]:
training_sequence = []
for sentence in input_numerical_sentence:
  for i in range(1 , len(sentence)):
    training_sequence.append(sentence[:i+1])


In [49]:
training_sequence

[[1, 2],
 [1, 2, 3],
 [4, 5],
 [4, 5, 2],
 [4, 5, 2, 6],
 [4, 5, 2, 6, 7],
 [4, 5, 2, 6, 7, 8],
 [4, 5, 2, 6, 7, 8, 9],
 [4, 5, 2, 6, 7, 8, 9, 10],
 [4, 5, 2, 6, 7, 8, 9, 10, 11],
 [4, 5, 2, 6, 7, 8, 9, 10, 11, 3],
 [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12],
 [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13],
 [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14],
 [4, 5, 2, 6, 7, 8, 9, 10, 11, 3, 12, 13, 14, 15],
 [2, 6],
 [2, 6, 16],
 [2, 6, 16, 17],
 [2, 6, 16, 17, 18],
 [2, 6, 16, 17, 18, 19],
 [2, 6, 16, 17, 18, 19, 20],
 [2, 6, 16, 17, 18, 19, 20, 21],
 [2, 6, 16, 17, 18, 19, 20, 21, 22],
 [2, 6, 16, 17, 18, 19, 20, 21, 22, 23],
 [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24],
 [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
 [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18],
 [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26],
 [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27],
 [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18, 26, 27, 28],
 [2, 6, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 18

In [50]:
len(training_sequence)

942

In [51]:
len_list = []
for sequence in training_sequence:
  len_list.append(len(sequence))

max(len_list)

62

In [52]:
padding_training_sequence = []
for sequence in training_sequence:
  padding_training_sequence.append(([0]*(max(len_list) - len(sequence)) + sequence))

In [53]:
padding_training_sequence

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  4,
  5],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  

In [54]:
len(padding_training_sequence[70])

62

In [55]:
padded_training_sequence = torch.tensor(padding_training_sequence, dtype=torch.long)

In [56]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287],
        [  0,   0,   0,  ..., 286, 287, 288]])

In [71]:
X = padded_training_sequence[:, :-1]
y = padded_training_sequence[: , - 1]

In [58]:
X


tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   0,   0,   4],
        ...,
        [  0,   0,   0,  ...,   0, 285, 176],
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287]])

In [59]:
y

tensor([  2,   3,   5,   2,   6,   7,   8,   9,  10,  11,   3,  12,  13,  14,
         15,   6,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  18,  26,
         27,  28,  29,  30,   5,   2,  31,  32,  27,   2,   6,  33,  31,  32,
         27,   2,   6,   5,  34,  35,  30,  36,   2,  31,   6,   7,  37,  38,
         39,  34,  40,  28,  41,  12,  42,  30,  15,   5,   2,  43,  27,   2,
         11,   3,  33,  45,  46,  47,   2,  48,  49,  50,  52,  53,   8,   9,
         10,  54,   8,   9,  10,   8,  57,  58,  60,  59,  64,  65,  66,   2,
         67,  43,  68,  69,  70,  50,  71,  72,  58,  73,  74,  46,  17,  75,
         27,  76,   3,  33,  78,  74,  73,  72,  58,  79,  80,  81,  17,  75,
         27,  76,   3,  82,  83,  84,  30,  85,  86,  87,  17,  88,  89,  33,
         45,  86,  90,  17,  91,  27,   2,  89,  33,  93,  94,  95,  80,  96,
         78,  36,  97,  85,  22,  87,  17,  89,  22,  65,  98,  99,  73, 100,
          2,  91,  30,  65,  86, 101,   2, 102, 103,  33,  76, 1

In [60]:
class CustomDataset(Dataset):

  def __init__(self , X, y):
    self.X = X
    self.y = y

  def __len__(self):
    return X.shape[0]

  def __getitem__(self, index):
    return self.X[index] , self.y[index]

In [61]:
dataset = CustomDataset(X , y)

In [62]:
dataloader = DataLoader(dataset , batch_size=32 , shuffle=True)

In [ ]:
import torch

In [101]:
class LSTMModel(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size , embedding_dim=100)
    self.lstm = nn.LSTM(100 , 150, batch_first=True)
    self.linear = nn.Linear(150 , vocab_size)

  def forward(self , x):
    embedded = self.embedding(x)
    indermeditate_state , (final_hidden , final_cell) = self.lstm(embedded)
    prediction = self.linear(final_hidden.squeeze(0))
    return prediction


In [97]:
x = nn.Embedding(289  , 100)
y = nn.LSTM(100 , 150 , batch_first=True)
z = nn.Linear(150, 289)

In [84]:
a = dataset[0][0].unsqueeze(0)
a.shape

torch.Size([1, 61])

In [81]:
x(a)

tensor([[[ 0.9623,  0.3832, -0.3761,  ...,  1.6306, -0.3373,  0.1393],
         [ 0.9623,  0.3832, -0.3761,  ...,  1.6306, -0.3373,  0.1393],
         [ 0.9623,  0.3832, -0.3761,  ...,  1.6306, -0.3373,  0.1393],
         ...,
         [ 0.9623,  0.3832, -0.3761,  ...,  1.6306, -0.3373,  0.1393],
         [ 0.9623,  0.3832, -0.3761,  ...,  1.6306, -0.3373,  0.1393],
         [ 0.2163, -0.7501, -0.1652,  ...,  0.4153,  0.3616,  0.5463]]],
       grad_fn=<EmbeddingBackward0>)

In [82]:
x(a).shape

torch.Size([1, 61, 100])

In [85]:
b = x(a)

In [86]:
y(b)

(tensor([[[-0.0984,  0.1048, -0.0585,  ...,  0.0909, -0.0167,  0.0852],
          [-0.1457,  0.1518, -0.0939,  ...,  0.1502, -0.0294,  0.1222],
          [-0.1705,  0.1732, -0.1152,  ...,  0.1847, -0.0385,  0.1383],
          ...,
          [-0.1996,  0.1929, -0.1505,  ...,  0.2296, -0.0562,  0.1549],
          [-0.1996,  0.1929, -0.1505,  ...,  0.2296, -0.0562,  0.1549],
          [-0.0121, -0.0401, -0.1308,  ...,  0.2562, -0.0414,  0.1943]]],
        grad_fn=<TransposeBackward0>),
 (tensor([[[-1.2064e-02, -4.0127e-02, -1.3078e-01, -1.0086e-01,  3.6516e-02,
             9.1008e-02,  5.8201e-02, -2.9741e-01,  8.2741e-02,  4.7472e-02,
             2.0649e-01,  1.7500e-01, -8.9699e-02, -2.3957e-01,  2.0813e-01,
            -1.1515e-01, -7.8439e-02,  2.9780e-02, -2.1603e-01,  2.1797e-01,
            -2.4854e-01,  9.3220e-02, -3.8655e-02, -4.6565e-02,  7.1243e-02,
             2.1642e-02,  1.4893e-01,  3.8066e-02,  1.5589e-01, -6.7261e-03,
            -2.5194e-02,  2.2376e-01, -6.6006e-02,

In [88]:
len(y(b))

2

In [89]:
c ,d = y(b)
#c is a set of all intermediate state

In [90]:
c.shape

torch.Size([1, 61, 150])

In [92]:
len(d)

2

In [93]:
e,f = d

In [94]:
e.shape

torch.Size([1, 1, 150])

In [96]:
f.shape

torch.Size([1, 1, 150])

In [100]:
z(f).squeeze(0).shape

torch.Size([1, 289])

In [102]:
model = LSTMModel(len(vocab))

In [104]:
epochs = 50
learning_rate = 0.001
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters() , lr=learning_rate)

In [106]:
#training loop
for epoch in range(epochs):
  total_loss = 0
  for batch_x , batch_y in dataloader:
    optimizer.zero_grad()
    output = model(batch_x)
    loss = criterion (output, batch_y)
    loss.backward()
    optimizer.step()
    total_loss = total_loss+ loss.item()
  print(f"Epoch: {epoch} Loss: {total_loss : .4f}")

Epoch: 0 Loss:  165.0470
Epoch: 1 Loss:  145.8425
Epoch: 2 Loss:  134.5733
Epoch: 3 Loss:  122.2667
Epoch: 4 Loss:  110.6279
Epoch: 5 Loss:  99.1317
Epoch: 6 Loss:  88.3459
Epoch: 7 Loss:  77.9169
Epoch: 8 Loss:  69.1173
Epoch: 9 Loss:  61.2655
Epoch: 10 Loss:  54.3062
Epoch: 11 Loss:  47.5626
Epoch: 12 Loss:  41.7720
Epoch: 13 Loss:  36.8075
Epoch: 14 Loss:  32.4580
Epoch: 15 Loss:  28.5790
Epoch: 16 Loss:  25.0179
Epoch: 17 Loss:  22.2861
Epoch: 18 Loss:  19.7020
Epoch: 19 Loss:  17.6682
Epoch: 20 Loss:  15.8161
Epoch: 21 Loss:  14.5238
Epoch: 22 Loss:  13.1659
Epoch: 23 Loss:  12.0762
Epoch: 24 Loss:  11.0314
Epoch: 25 Loss:  10.2893
Epoch: 26 Loss:  9.7205
Epoch: 27 Loss:  9.0507
Epoch: 28 Loss:  8.4139
Epoch: 29 Loss:  7.9454
Epoch: 30 Loss:  7.7024
Epoch: 31 Loss:  7.1142
Epoch: 32 Loss:  6.8388
Epoch: 33 Loss:  6.7384
Epoch: 34 Loss:  6.2746
Epoch: 35 Loss:  6.0238
Epoch: 36 Loss:  5.8721
Epoch: 37 Loss:  5.7614
Epoch: 38 Loss:  5.5150
Epoch: 39 Loss:  5.3627
Epoch: 40 Loss:  5.

In [151]:

#prediction
def prediction(model , vocab , text ):
  #tokenize
  tokenized_text = word_tokenize(text)

  tokenized_text = (" ").join(tokenized_text)
  # text -> numerical indices
  numerical_text = text_to_indices(tokenized_text , vocab)

  #padding
  padding_text = [0]*(max(len_list) - len(numerical_text)) +numerical_text
  padding_text  = torch.tensor(padding_text , dtype=torch.long).unsqueeze(0)


  #send to model
  model = LSTMModel(vocab_size=len(vocab))
  output= model(padding_text)
  val , idx = torch.max(output , dim = 1)
  idx = idx.item()
  return text + " " + (list(vocab.keys())[idx])

  #predicted index


  #merge with text

In [161]:
text = "the course follows"
prediction(model , vocab , text)

'the course follows studies'

In [159]:
import time

In [171]:
number_of_prediction = 20
text = "what"
for i in range(number_of_prediction):
  output = prediction(model , vocab , text)
  print(output)
  text = output
  time.sleep(0.5)

what calls
what calls hours
what calls hours where
what calls hours where by
what calls hours where by monthly
what calls hours where by monthly content
what calls hours where by monthly content following
what calls hours where by monthly content following assistance
what calls hours where by monthly content following assistance criterias
what calls hours where by monthly content following assistance criterias 5600
what calls hours where by monthly content following assistance criterias 5600 purchase
what calls hours where by monthly content following assistance criterias 5600 purchase =
what calls hours where by monthly content following assistance criterias 5600 purchase = roughly
what calls hours where by monthly content following assistance criterias 5600 purchase = roughly ask
what calls hours where by monthly content following assistance criterias 5600 purchase = roughly ask not
what calls hours where by monthly content following assistance criterias 5600 purchase = roughly ask n