In [13]:
import torch
import torch.nn as nn 
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [158]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [159]:
df.drop(columns=['Unnamed: 32', 'id'], inplace=True)

In [160]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2, random_state=42, stratify=df.iloc[:, 0])

In [161]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [162]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [163]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [164]:
X_train_tensor.shape

torch.Size([455, 30])

In [165]:
import torch
import torch.nn as nn   

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        
        self.loss = nn.BCELoss()
 
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    def loss(self, pred, target):
        return self.loss(pred, target)

In [166]:
model = Model(X_train_tensor.shape[1])
model(X_train_tensor)

tensor([[0.4648],
        [0.3845],
        [0.5337],
        [0.5370],
        [0.3263],
        [0.5576],
        [0.4983],
        [0.5277],
        [0.4077],
        [0.3362],
        [0.3597],
        [0.3502],
        [0.4963],
        [0.4919],
        [0.4357],
        [0.4568],
        [0.4815],
        [0.5258],
        [0.4593],
        [0.4285],
        [0.3661],
        [0.5052],
        [0.4214],
        [0.5731],
        [0.6068],
        [0.4032],
        [0.5352],
        [0.3873],
        [0.3665],
        [0.4364],
        [0.4542],
        [0.5792],
        [0.7975],
        [0.3574],
        [0.5093],
        [0.4196],
        [0.5308],
        [0.4028],
        [0.4162],
        [0.4495],
        [0.4690],
        [0.4788],
        [0.4845],
        [0.3992],
        [0.4876],
        [0.4327],
        [0.5794],
        [0.4547],
        [0.4008],
        [0.3365],
        [0.3886],
        [0.3969],
        [0.4065],
        [0.4303],
        [0.4107],
        [0

In [167]:
model.linear.weight

Parameter containing:
tensor([[ 0.0474, -0.0225,  0.1492, -0.1157, -0.0101, -0.0542, -0.0192, -0.1352,
         -0.0011,  0.1687, -0.0011,  0.0087,  0.0094,  0.1668, -0.1603,  0.0178,
         -0.0629, -0.1246,  0.0285,  0.0995, -0.1779, -0.0211, -0.0454,  0.0586,
         -0.0961,  0.1018,  0.1433,  0.0181,  0.1060,  0.0151]],
       requires_grad=True)

In [168]:
model.linear.bias

Parameter containing:
tensor([-0.1373], requires_grad=True)

In [169]:
from torchinfo import summary
summary(model, input_size=(1, X_train_tensor.shape[1]))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [1, 1]                    --
├─Linear: 1-1                            [1, 1]                    31
├─Sigmoid: 1-2                           [1, 1]                    --
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [170]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 16)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(16, 8)
        self.linear3 = nn.Linear(8, 1)
        self.sigmoid = nn.Sigmoid()
        
        self.loss = nn.BCELoss()
 
    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.relu(out)
        out = self.linear3(out)
        out = self.sigmoid(out)
        
        return out
    def loss(self, pred, target):
        return self.loss(pred, target)

In [171]:
model = Model(X_train_tensor.shape[1])
model(X_train_tensor)

tensor([[0.5858],
        [0.5744],
        [0.5736],
        [0.6000],
        [0.5750],
        [0.6108],
        [0.5751],
        [0.5839],
        [0.5688],
        [0.5779],
        [0.5756],
        [0.5830],
        [0.5597],
        [0.5924],
        [0.5759],
        [0.5843],
        [0.5783],
        [0.5762],
        [0.5753],
        [0.5723],
        [0.5748],
        [0.5679],
        [0.5699],
        [0.5779],
        [0.6085],
        [0.5701],
        [0.5860],
        [0.5786],
        [0.5795],
        [0.5947],
        [0.5487],
        [0.5720],
        [0.6472],
        [0.5702],
        [0.5728],
        [0.5751],
        [0.5797],
        [0.5875],
        [0.5908],
        [0.5797],
        [0.5762],
        [0.5657],
        [0.5738],
        [0.5662],
        [0.5699],
        [0.5722],
        [0.5970],
        [0.5746],
        [0.5904],
        [0.5811],
        [0.5893],
        [0.5672],
        [0.5697],
        [0.5687],
        [0.5764],
        [0

In [172]:
from torchinfo import summary
summary(model, input_size=(1, X_train_tensor.shape[1]))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [1, 1]                    --
├─Linear: 1-1                            [1, 16]                   496
├─ReLU: 1-2                              [1, 16]                   --
├─Linear: 1-3                            [1, 8]                    136
├─ReLU: 1-4                              [1, 8]                    --
├─Linear: 1-5                            [1, 1]                    9
├─Sigmoid: 1-6                           [1, 1]                    --
Total params: 641
Trainable params: 641
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [173]:
model.linear1.weight

Parameter containing:
tensor([[ 0.1431, -0.1024, -0.1019,  0.0380, -0.0035, -0.0248, -0.0536,  0.0995,
          0.1822,  0.0943, -0.1582, -0.0642, -0.1320,  0.0257, -0.0556, -0.1643,
         -0.0509, -0.0042, -0.0232, -0.0246, -0.0339, -0.0110,  0.0352,  0.1629,
          0.0674, -0.0888, -0.0648,  0.0834, -0.0495, -0.0694],
        [-0.0706, -0.1764,  0.0485, -0.1763,  0.0957,  0.1450, -0.1709,  0.0914,
         -0.0494,  0.0445,  0.1712, -0.1580, -0.1749, -0.1439,  0.1028,  0.0709,
         -0.0548, -0.1494, -0.0474,  0.1005, -0.1451,  0.1805, -0.0912, -0.0987,
          0.0253,  0.1486, -0.0066,  0.1622, -0.1357, -0.0958],
        [-0.1097,  0.0111, -0.0444, -0.0425,  0.1194, -0.1726,  0.0404,  0.0797,
         -0.1062,  0.0200, -0.1666, -0.0631, -0.0584, -0.0569,  0.1392, -0.0562,
          0.1482,  0.0069, -0.0653,  0.0859, -0.0264, -0.0980, -0.0040,  0.1805,
          0.0699,  0.0665,  0.0580, -0.0423,  0.0810, -0.1482],
        [-0.1790,  0.1328, -0.1706,  0.1360, -0.1786,  0.

In [174]:
model.linear1.weight.shape

torch.Size([16, 30])

In [175]:
model.linear1.bias.shape

torch.Size([16])

In [176]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 16),
            nn.ReLU(),
            nn.Linear(16, 8),
            nn.ReLU(),
            nn.Linear(8, 1),
            nn.Sigmoid()
        )
        self.criterion = nn.BCELoss()
        
 
    def forward(self, features):
        out = self.network(features)
        
        return out
  


In [185]:
model = Model(X_train_tensor.shape[1])
model(X_train_tensor)

tensor([[0.4516],
        [0.4606],
        [0.4696],
        [0.4026],
        [0.4103],
        [0.2140],
        [0.4608],
        [0.4714],
        [0.4673],
        [0.4286],
        [0.4050],
        [0.3250],
        [0.4474],
        [0.4572],
        [0.4597],
        [0.4630],
        [0.4611],
        [0.4479],
        [0.4576],
        [0.4521],
        [0.4597],
        [0.4610],
        [0.4372],
        [0.4137],
        [0.2429],
        [0.4518],
        [0.4608],
        [0.4553],
        [0.4035],
        [0.3558],
        [0.4678],
        [0.4238],
        [0.3073],
        [0.4291],
        [0.4574],
        [0.4570],
        [0.4679],
        [0.4630],
        [0.4308],
        [0.4696],
        [0.4824],
        [0.4623],
        [0.4521],
        [0.4765],
        [0.4568],
        [0.4542],
        [0.3475],
        [0.4581],
        [0.4256],
        [0.4479],
        [0.4365],
        [0.4528],
        [0.4615],
        [0.4749],
        [0.4557],
        [0

In [186]:
from torchinfo import summary
summary(model, input_size=(1, X_train_tensor.shape[1]))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [1, 1]                    --
├─Sequential: 1-1                        [1, 1]                    --
│    └─Linear: 2-1                       [1, 16]                   496
│    └─ReLU: 2-2                         [1, 16]                   --
│    └─Linear: 2-3                       [1, 8]                    136
│    └─ReLU: 2-4                         [1, 8]                    --
│    └─Linear: 2-5                       [1, 1]                    9
│    └─Sigmoid: 2-6                      [1, 1]                    --
Total params: 641
Trainable params: 641
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [187]:
learning_rate = 0.1
epochs = 10
loss_function = nn.BCELoss()

In [188]:
import torch.optim as optim
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [189]:
for epochs in range(epochs):
    pred = model(X_train_tensor)
    loss = loss_function(pred.view(-1), y_train_tensor.view(-1))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
  
    print(f'Epoch {epochs+1} Loss: {loss.item()}')


Epoch 1 Loss: 0.7096940875053406
Epoch 2 Loss: 0.5018615126609802
Epoch 3 Loss: 0.2121233195066452
Epoch 4 Loss: 0.1400049924850464
Epoch 5 Loss: 0.11993232369422913
Epoch 6 Loss: 0.10215137898921967
Epoch 7 Loss: 0.08759744465351105
Epoch 8 Loss: 0.08766462653875351
Epoch 9 Loss: 0.07885690778493881
Epoch 10 Loss: 0.06446459889411926


In [190]:
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.7).int()

In [191]:
accuracy = (y_pred == y_test_tensor).float().mean()

In [192]:
accuracy

tensor(0.5416)