In [2]:
import torch

# Define a tensor
tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)

print(tensor)

tensor([[1., 2.],
        [3., 4.]])


In [3]:
torch.empty(2, 3)

tensor([[-4.6479e+18,  1.8469e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
a = torch.tensor([[1, 2], [3, 4]])

In [5]:
type(a)

torch.Tensor

In [7]:
torch.rand(2,3)

tensor([[0.7835, 0.9349, 0.3892],
        [0.6364, 0.1418, 0.1311]])

In [8]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [9]:
torch.linspace(1, 10, 5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [10]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
torch.full((2, 3), 5)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [13]:
#tensor shapes
x= torch.tensor([[1, 2], [3, 4]])

In [14]:
x.shape

torch.Size([2, 2])

In [15]:
x.size

<function Tensor.size>

In [18]:
torch.empty_like(x)

tensor([[0, 0],
        [0, 0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0],
        [0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1],
        [1, 1]])

In [25]:
#TENSOR DATA TYPES
x.dtype

torch.int64

In [26]:
y = torch.tensor([[1.5, 2.3], [3.4, 4.7]], dtype=torch.int32)

In [27]:
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [31]:

x=torch.tensor([[1.5, 2.3], [3.4, 4.7]], dtype=torch.float32)

In [32]:
x

tensor([[1.5000, 2.3000],
        [3.4000, 4.7000]])

In [33]:
x.to(torch.int32)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [35]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.4322, 0.1825],
        [0.4272, 0.7887]])

In [37]:

#MATHEMATICAL OPERATIONS
x= torch.rand(2,2)

In [43]:
x

tensor([[0.2559, 0.7720],
        [0.1568, 0.4874]])

In [46]:
#scalar operations
x+2
x-2
x/3
x*4

tensor([[1.0238, 3.0881],
        [0.6273, 1.9494]])

In [47]:
x**2

tensor([[0.0655, 0.5960],
        [0.0246, 0.2375]])

In [49]:
a = torch.tensor([[1, 2], [3, 4]])
b= torch.tensor([[5, 6], [7, 8]])

In [50]:
a*b

tensor([[ 5, 12],
        [21, 32]])

In [51]:
a**b

tensor([[    1,    64],
        [ 2187, 65536]])

In [52]:
a%b

tensor([[1, 2],
        [3, 4]])

In [53]:
torch.neg(a)

tensor([[-1, -2],
        [-3, -4]])

In [56]:
x = torch.rand((2,2), dtype=torch.float32)
x

tensor([[0.9468, 0.6157],
        [0.6299, 0.9876]])

In [55]:
torch.round(x)

tensor([[0., 0.],
        [1., 1.]])

In [57]:
torch.clamp(x, min=0.2, max=0.8)

tensor([[0.8000, 0.6157],
        [0.6299, 0.8000]])

In [69]:
#reduction operations
e = torch.rand((2, 3), dtype=torch.float32)
e

tensor([[0.8269, 0.0231, 0.4309],
        [0.7658, 0.8663, 0.7352]])

In [70]:
torch.sum(e)

tensor(3.6483)

In [71]:
torch.sum(e, dim=0)

tensor([1.5927, 0.8894, 1.1661])

In [72]:
torch.sum(e, dim=1)

tensor([1.2808, 2.3674])

In [73]:
torch.mean(e)

tensor(0.6080)

In [76]:
torch.median(e)


tensor(0.7352)

In [77]:
torch.matmul(a,b)

tensor([[19, 22],
        [43, 50]])

In [78]:
torch.max(e)
torch.min(e)


tensor(0.0231)

In [79]:
torch.argmax(e)

tensor(4)

In [80]:
torch.argmin(e)

tensor(1)

In [96]:
i = torch.tensor(([[1, 2], [3, 4]]), dtype=torch.float32)
j = torch.tensor([[5, 6], [7, 8]])

In [97]:
i>j

tensor([[False, False],
        [False, False]])

In [98]:
i == j

tensor([[False, False],
        [False, False]])

In [99]:
i!=j

tensor([[True, True],
        [True, True]])

In [100]:
#special function 
torch.exp(i)

tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5981]])

In [101]:
torch.log(i)

tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])

In [102]:
torch.sqrt(i)

tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])

In [103]:
torch.sigmoid(i)

tensor([[0.7311, 0.8808],
        [0.9526, 0.9820]])

In [104]:
torch.softmax(i , dim=1)

tensor([[0.2689, 0.7311],
        [0.2689, 0.7311]])

In [105]:
torch.relu(i)

tensor([[1., 2.],
        [3., 4.]])

In [107]:
i.add_(j)

tensor([[ 6.,  8.],
        [10., 12.]])

In [108]:
i

tensor([[ 6.,  8.],
        [10., 12.]])

In [109]:
i.relu_()

tensor([[ 6.,  8.],
        [10., 12.]])

In [112]:
i.sigmoid_()


tensor([[0.9975, 0.9997],
        [1.0000, 1.0000]])

In [114]:
#copying of tensor
a =torch.rand((3,3), dtype=torch.float32)

In [115]:
b=a
b

tensor([[0.4149, 0.1916, 0.8850],
        [0.6717, 0.7811, 0.9678],
        [0.0939, 0.2783, 0.6625]])

In [116]:
a[0][0] = 0

In [117]:
a

tensor([[0.0000, 0.1916, 0.8850],
        [0.6717, 0.7811, 0.9678],
        [0.0939, 0.2783, 0.6625]])

In [118]:
b

tensor([[0.0000, 0.1916, 0.8850],
        [0.6717, 0.7811, 0.9678],
        [0.0939, 0.2783, 0.6625]])

In [119]:
id(a)

2251622678704

In [120]:
id(b)

2251622678704

In [121]:
b = a.clone()

In [122]:
a[1][1] = 0

In [123]:
a


tensor([[0.0000, 0.1916, 0.8850],
        [0.6717, 0.0000, 0.9678],
        [0.0939, 0.2783, 0.6625]])

In [124]:
b

tensor([[0.0000, 0.1916, 0.8850],
        [0.6717, 0.7811, 0.9678],
        [0.0939, 0.2783, 0.6625]])

In [130]:
#ON GPU
#torch.cuda.is_available()
#device = torch.device("cuda")
# torch.rand((2, 3), device=device)

In [131]:
#reshaping tensors

In [132]:
a = torch.ones(4,4)

In [133]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [134]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [136]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.3185, 0.0736, 0.8207, 0.0632],
         [0.2209, 0.5754, 0.4852, 0.9558],
         [0.7107, 0.9437, 0.9792, 0.3233]],

        [[0.9831, 0.1146, 0.0751, 0.5488],
         [0.5408, 0.7843, 0.3529, 0.1745],
         [0.9341, 0.4805, 0.6665, 0.2746]]])

In [137]:
b.permute(2, 0 , 1)

tensor([[[0.3185, 0.2209, 0.7107],
         [0.9831, 0.5408, 0.9341]],

        [[0.0736, 0.5754, 0.9437],
         [0.1146, 0.7843, 0.4805]],

        [[0.8207, 0.4852, 0.9792],
         [0.0751, 0.3529, 0.6665]],

        [[0.0632, 0.9558, 0.3233],
         [0.5488, 0.1745, 0.2746]]])

In [138]:
b.permute(2, 0, 1).shape

torch.Size([4, 2, 3])

In [141]:

c = torch.rand(226, 226, 3)

In [143]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [144]:
d= torch.rand(1,20)

In [145]:
d.squeeze(0).shape

torch.Size([20])

In [146]:
#numpy and pytorch

In [147]:
import numpy as np 


In [148]:
a= torch.rand(2, 3)

In [149]:
a

tensor([[0.0823, 0.5872, 0.2641],
        [0.4957, 0.2770, 0.2901]])

In [151]:
b = a.numpy()

In [154]:
type(b)

numpy.ndarray

In [155]:
c= np.zeros((2, 3))

In [156]:
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [158]:
torch.from_numpy(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)